[package]
name = "liquid-glass-render"
description = "GPU compositor foundation for Liquid Glass."
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
liquid-glass-scene = { path = "../liquid-glass-scene", version = "0.1.0" }

[lints]
workspace = true

