[package]
name = "bmol-iced"
description = "Modern Apple-style Liquid Glass UI and frameless window toolkit for Iced."
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
liquid-rs = { git = "https://github.com/Erizeez/liquid-rs", branch = "main" }
liquid-glass-animation = { git = "https://github.com/Erizeez/liquid-rs", branch = "main" }
squircle-rs = { git = "https://github.com/Erizeez/squircle-rs", tag = "v0.1.2" }
liquid-glass-render = { git = "https://github.com/Erizeez/liquid-rs", branch = "main" }
liquid-glass-scene = { git = "https://github.com/Erizeez/liquid-rs", branch = "main" }
bmol-window-shell = { git = "https://github.com/Erizeez/bmol-window-shell", branch = "main" }
bmol-window-platform = { git = "https://github.com/Erizeez/bmol-window-shell", branch = "main" }
bmol-window-native = { git = "https://github.com/Erizeez/bmol-window-shell", branch = "main" }
bmol-designs = { git = "https://github.com/Erizeez/bmol-designs", tag = "v0.1.6" }
iced = { version = "0.14.0", default-features = false, features = ["advanced", "canvas", "thread-pool", "svg", "image-without-codecs", "x11", "wayland"] }
image = { version = "0.25.10" }
squircle-icon-rs = { git = "https://github.com/Erizeez/squircle-icon-rs", tag = "v0.1.14" }
vibrancy-rs = { git = "https://github.com/Erizeez/vibrancy-rs", tag = "v0.1.1" }
liquid-glass-ui = { git = "https://github.com/Erizeez/bmol-glass-ui", tag = "v0.1.5" }

[lints]
workspace = true
