[package]
name = "bmol-iced"
description = "Modern Apple-style Liquid Glass UI and frameless window toolkit for Iced."
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
liquid-rs = { path = "../../../liquid-rs/crates/liquid-rs", version = "0.1.0" }
liquid-glass-animation = { path = "../../../liquid-rs/crates/liquid-glass-animation", version = "0.1.0" }
squircle-rs = { path = "../../../squircle-rs", version = "0.1.1" }
liquid-glass-render = { path = "../../../liquid-rs/crates/liquid-glass-render", version = "0.1.0" }
liquid-glass-scene = { path = "../../../liquid-rs/crates/liquid-glass-scene", version = "0.1.0" }
bmol-window-shell = { path = "../../../bmol-window-shell/crates/bmol-window-shell", version = "0.1.0" }
bmol-window-platform = { path = "../../../bmol-window-shell/crates/bmol-window-platform", version = "0.1.0" }
bmol-window-native = { path = "../../../bmol-window-shell/crates/bmol-window-native", version = "0.1.0" }
bmol-designs = { path = "../../../bmol-designs", version = "0.1.0" }
liquid-glass-ui = { path = "../liquid-glass-ui", version = "0.1.0" }

[lints]
workspace = true
