[package]
name = "liquid-glass"
description = "Rust Liquid Glass UI framework facade."
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
liquid-glass-animation = { path = "../liquid-glass-animation", version = "0.1.0" }
liquid-glass-platform = { path = "../liquid-glass-platform", version = "0.1.0" }
liquid-glass-render = { path = "../liquid-glass-render", version = "0.1.0" }
liquid-glass-scene = { path = "../liquid-glass-scene", version = "0.1.0" }
liquid-glass-ui = { path = "../liquid-glass-ui", version = "0.1.0" }

[lints]
workspace = true

