[package]
name = "liquid-glass-ui"
description = "UI-facing Liquid Glass components and builders."
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
iced = { version = "0.14.0", default-features = false, features = ["advanced", "canvas", "thread-pool", "svg", "image-without-codecs", "x11", "wayland"] }
liquid-glass-scene = { path = "../liquid-glass-scene", version = "0.1.0" }

[lints]
workspace = true
